### PR TITLE
Delete files when corresponding db entry is removed

### LINKED ISSUE #53: Delete files when corresponding database entry is removed

### PR DESCRIPTION
**Pull request by bnaul**
Uses `playhouse.signals` to implement delete hooks for `File`. `Featureset`, `Model`, and `Prediction` follow from cascading on delete, but `Dataset` needs its own hook since there is an intermediary table.

Closes #53.

### CODE REVIEW

**Comment by bnaul** [comment]
@stefanv @acrellin should there be a test for this? We currently don't directly test any of the logic that lives in `models.py`; maybe this should be a new test file...?

**Comment by acrellin** [comment]
@bnaul was just thinking we should add a test for this

**Comment by bnaul** [comment]
Added a test. Ready for y'all @stefanv @acrellin

**Comment by acrellin** [comment]
@bnaul Not sure about `test_models` -> `test_build_model` because that module tests a lot more than just building a model; it tests the functionality of the models tab in general. Maybe add `frontend` or `tab` to the original module name or something rather than this?

**Comment by bnaul** [comment]
All that functionality is related to model building, though, right...? It's
annoying that both things are called models, not sure how to best
disambiguate. Prefixing every file sounds a little clunky...

**Comment by acrellin** [comment]
Or a `selenium` subdirectory?

**Comment by bnaul** [comment]
Increased a test timeout to make the tests more reliable; good to go now.

**Pull request merged**
