### PR TITLE
Separating presentational and container components

### PR DESCRIPTION
**Pull request by acrellin**
This is just the `Projects.jsx` refactor.

### CODE REVIEW

**Comment by bnaul** [comment]
Is it definitely necessary to have everything in its own directory? It's hard for me to see the advantage of that.

**Comment by acrellin** [comment]
@bnaul I think the idea is to eventually put all of the redux code
(actions, reducers, etc) related to each component into that component's respective
directory.

**Comment by acrellin** [comment]
Closes #255

**Comment by stefanv** [comment]
@acrellin I haven't thought about this for a while, but Andy mentioned https://github.com/react-boilerplate/react-boilerplate to me in https://github.com/cesium-ml/baselayer/issues/41  It may be worth to just double check how they do things (for all I know it's the same as in this refactor).

**Comment by acrellin** [comment]
@stefanv Looks like we're using the same structure

**Comment by acrellin** [comment]
@stefanv this is ready for review

**Comment by stefanv** [comment]
We've now moved to functional components + redux logic in `ducks`.

**Pull request closed without merging**
