### PR TITLE
WIP Port plotly to bokeh

### PR DESCRIPTION
**Pull request by hatsy**

### CODE REVIEW

**Comment by bnaul** [comment]
Can you rebase on master?

**Comment by hatsy** [comment]
@bnaul I think this is already rebased on master, I'll look into why the build fails, from a quick look it seems like a frontend test is broken.

**Comment by acrellin** [comment]
@hatsy the failing test needs to be updated - the element it's looking for is the container for the old plot. The test just checked that the plot container was rendered. You'll need to figure out how to test that the new plot is being rendered, and update that test accordingly.

**Comment by bnaul** [comment]
The commit list is very long and goes back to Feb 24 so I think something
is off...

**Comment by hatsy** [comment]
Reopened a seperate pull request #185  rebased on master.

**Pull request closed without merging**
