### PR TITLE
Replace PhantomJS with Chromium + xvfb

### PR DESCRIPTION
**Pull request by acrellin**
Add back in tests that weren't working with PhantomJS

### CODE REVIEW

**Comment by bnaul** [comment]
Just had a realization: why bother with hacking an `xvfb` replacement on OS X? How about just a flag of some kind to let it run headfully? That's probably what I'd want anyway for debugging, headless could just be for Travis...

**Comment by stefanv** [comment]
Agreed, Brett. 

Ari, this looks good!

**Comment by acrellin** [comment]
How about just a check to see if `xvfb` is installed, and only use it if so?

**Comment by bnaul** [comment]
All the same to me; it seems like you would want to watch the tests sometimes maybe? Two targets would be easiest then, but if not then might as well merge them.

**Comment by acrellin** [comment]
Yeah I do run them headfully sometimes to see what's going on. Two targets it is.

**Comment by bnaul** [comment]
Only other thing: could you add a check to make sure `chromedriver` exists and, if not, just error out instead of running the tests?

**Pull request merged**
