### PR TITLE
add and drop tables

### PR DESCRIPTION
**Pull request by sonajeswani**
I added python commands in the file in order to add and drop the tables in the database. This is similar to what we did in the db_drop file.

### CODE REVIEW

**Comment by stefanv** [comment]
@sonajeswani Please take a look at the Travis-CI feedback.

Executing those statements in three invocations of Python definitely will not work.

**Comment by bnaul** [comment]
@sonajeswani Also, it's much faster to run a command locally and make sure that it works before you create a pull request. There's really never any reason not to do this.

**Comment by sonajeswani** [comment]
@stefanv @bnaul I should have tested it first! Sorry about that. I fixed the issues so it should be creating the tables.

**Comment by bnaul** [comment]
Doesn't seem like this is going anywhere so I'll just take care of it.

**Pull request closed without merging**
