### PR TITLE
Require labeled training data when building model; add associated test

### LINKED ISSUE #92: Require labeled training data when building model
Currently the error provided is `Unknown label type: array([[nan], ..., [nan]])`.

### PR DESCRIPTION
**Pull request by acrellin**
Closes #92

### CODE REVIEW

**Review by bnaul — COMMENTED** [review]
I don't like needing to open the file twice, it would be better to do that in the rest of the async logic when the file is already open.

In fact, it probably makes more sense to just put this check in the library and have that raise the exception...

**Comment by bnaul** [comment]
Went ahead and added this: https://github.com/cesium-ml/cesium/pull/193

If you want to go ahead and merge that, then your tests here should still pass if you remove the changes to `model_handler` and keep the others. I think keeping the test is a good idea even if the change is made on the backend.

**Comment by bnaul** [comment]
@acrellin I uploaded `cesium==0.6.3` with the changes you just merged there; if you amend this and remove the `target` checking bit, the tests should all be happy and we can merge this.

**Comment by acrellin** [comment]
ok @bnaul, check it out when you have a sec

**Comment by bnaul** [comment]
@acrellin just did a release so you might wanna bump the library req to `0.6.4`, otherwise 👍

**Comment by acrellin** [comment]
@stefanv do you want to review this or should I just merge (Brett already approved)?

**Comment by stefanv** [comment]
Looks good!

**Pull request merged**
