### PR TITLE
Regenerate docker images

### PR DESCRIPTION
**Pull request by hatsy**
I've made the necessary changes to regenerate the docker images with the current codebase. 

Was tested manually (since the frontend tests can't be run against the docker images at the moment). 

To regenerate the docker image you can run 
> make docker-images

if you have edit rights to docker hub the new images will be pushed to docker hub. 

To run the images locally, from `./docker/` run:
> docker-compose up

You can then access Cesium on localhost:9000

### CODE REVIEW

**Review by bnaul — COMMENTED** [review]
What happened to the postgres image? Where does the init stuff happen now?

**Comment by hatsy** [comment]
As per the docker hub postgres documentation (https://hub.docker.com/_/postgres/):

"POSTGRES_USER
This optional environment variable is used in conjunction with POSTGRES_PASSWORD to set a user and its password. This variable will create the specified user with superuser power and a database with the same name. If it is not specified, then the default user of postgres will be used."

So setting this environment variable in the docker-compose file does the same thing as what was done in the database init.

**Comment by bnaul** [comment]
Ok, but there are other things happening in the setup of the `cesium/postgres` image that you removed here. Look at what's happening in `init-user-db.sh`; the database can't be used if you don't run those steps first.

**Comment by bnaul** [comment]
Also: I just tried to build this image locally and got
```
Traceback (most recent call last):
  File "./tools/silent_monitor.py", line 14, in <module>
    print('[\xb7] {}'.format(tag), end='')
UnicodeEncodeError: 'ascii' codec can't encode character '\xb7' in position 1: ordinal not in range(128)
make: *** [dependencies] Error 1
```

**Comment by bnaul** [comment]
At this point I already have my own working version from debugging these issues so I'm just going to push that.

**Comment by hatsy** [comment]
In my understanding the `init-user-db.sh`: 
- creates the user cesium
- creates the database cesium
- grants all privilege on the database cesium to user cesium

The environment variable `POSTGRES_USER=cesium` "create the specified user with superuser power and a database with the same name", which I think covers the above.

**Comment by hatsy** [comment]
Concerning the errors, I just rebased on master to be able to merge and that's where the error came from. I should have tested before pushing the rebased version. It worked on the previous state of master.

**Comment by bnaul** [comment]
Ah okay, that would be a good simplification if we could use the default postgres image (although using ours instead is probably like 5MB extra). Maybe we want to keep our own image around in case we want to modify the default config? @stefanv any preference?

**Comment by stefanv** [comment]
If we can use the default postgres, that'd be ideal.  I imagine back when we did all this, the init script was the preferred way of setting up the DB.

**Pull request closed without merging**
