### PR TITLE
Require that at least one feature be selected for successful Featurize form submission

### LINKED ISSUE #59: Forbid computing zero features
Users can deselect all features

### PR DESCRIPTION
**Pull request by acrellin**
Also remove unused actions.
Closes #59

### CODE REVIEW

**Comment by acrellin** [comment]
I'll also add a test for this

**Comment by stefanv** [comment]
:+1:

**Comment by acrellin** [comment]
Explored doing this client-side first, which seems much more difficult

**Comment by acrellin** [comment]
:green_heart:

**Pull request merged**
