### PR TITLE
Check dependency version when installing using pip

### PR DESCRIPTION
**Pull request by hatsy**
Changed how we install python dependencies from requirements.txt so that the version is no longer ignored. I used pkg_resources, a module of setuptools to simplify the code. A potential next step could be to port everything to setuptools.

### CODE REVIEW

**Comment by bnaul** [comment]
There's an extra `.pyc` file in here; we should probably add that to `.gitignore`.

Is it necessary to install `setuptools` inside the script? Seems like that would already be available in most cases.

**Comment by hatsy** [comment]
Build was failing because of intermittent tests

**Review by bnaul — APPROVED** [review]
@stefanv ?

**Comment by hatsy** [comment]
Actually I've realised that if there are multiple requirements unsatisfied this will only handle the first one. Let me correct that

**Comment by stefanv** [comment]
Great!  Will this re-install Cesium from Git each time, or is it happy once the dev version is installed?

I'm actually not quite sure what the correct behavior should be in this case; @bnaul ?

**Comment by bnaul** [comment]
@hatsy I spoke with @stefanv and I think we can just use `pip install -r requirements.txt` for this logic; the version you just uploaded doesn't work with `-e ...` requirements and I think we were just going to implement re-implementing `pip` ourselves.

**Pull request merged**
