### PR TITLE
Grab latest version of Webpack (and others)

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by MichaelTamaki** [comment]
Fixes #157

**Comment by bnaul** [comment]
I don't believe this will pass without also making the change from #156.

**Comment by bnaul** [comment]
@stefanv `webpack` is a persistent little guy it seems:
```
+make bundle
./node_modules/.bin/webpack
Hash: [1mbc8c80ff134cc758b6e1[22m
Version: webpack [1m1.13.2[22m
```

**Comment by stefanv** [comment]
We're green, @bnaul!

**Pull request merged**
