### PR TITLE
Updated installation instructions to run cesium_web locally

### PR DESCRIPTION
**Pull request by hatsy**
Updated the formatting and the instructions to run cesium_web locally on MacOS, the previous steps being incomplete and not clear. I tested those steps locally. 
Also updated the formatting for steps on Linux but didn't change or test those steps.

### CODE REVIEW

**Comment by MichaelTamaki** [comment]
Just wondering, did you have to also pip install xarray, sklearn, and/or scipy? I found that I was missing these dependencies.

**Comment by MichaelTamaki** [comment]
Also, to install Cesium, you need to pip install Cython.

**Comment by bnaul** [comment]
@MichaelTamaki Those are all dependencies of `cesium` which is in `requirements.txt`, so they should be added automatically. Perhaps they didn't because you were missing Cython?

Also, which Python are you using? There are wheels for 2.7 and 3.{4,5} but 3.6 was missing (just added it). Hopefully 3.6 or else I'm confused...?

**Comment by bnaul** [comment]
@hatsy I just bumped all my environments to 3.6 so let me walk through my steps and compare. Will make a couple of edits here and then we can merge.

**Comment by bnaul** [comment]
@stefanv The line `-e git://github.com/cesium-ml/cesium.git#egg=cesium` in `requirements.txt` is pretty annoying if you already have a local install of `cesium` (I have to just keep commenting it out). What if we changed it to a minimum version but changed the Travis config to manually install from the latest source? That seems like the best of both worlds.

**Comment by bnaul** [comment]
@stefanv another thing I noticed: if `make dependencies` fails to install the Python requirements, the process keeps going and installs all the JavaScript stuff, which can make you think that nothing went wrong (that's probably what happened to @MichaelTamaki). I'm going to change `install_deps.py` so that this doesn't happen.

**Comment by MichaelTamaki** [comment]
@bnaul Yeah, I think you're right that when `make dependencies` fails, it might mess up other dependencies. I had to make a new virtual environment and made sure to pip install Cython before running make dependencies. Maybe add Cython to requirements.txt before installing cesium?

**Comment by stefanv** [comment]
Yes, good idea (w.r.t pip/Travis install of Cesium).

**Comment by stefanv** [comment]
These changes look good; we may have to rebase on latest master.

**Pull request closed without merging**
