### PR TITLE
WIP: More consistent JavaScript syntax & formatting

### LINKED ISSUE #5: Add eslint configuration

### PR DESCRIPTION
**Pull request by acrellin**
Closes #5 

Run the linter with `node_modules/eslint/bin/eslint.js -c .eslintrc --ext .jsx,.js public/scripts/` (if `eslint` isn't already in your `PATH`) OR add a pre-commit hook by adding the following to your .git/hooks/pre-commit :

```
#!/bin/bash
# Pre-commit Git hook to run ESLint on JavaScript files.
#
# If you absolutely must commit without testing,
# use: git commit --no-verify (git commit -n)

filenames=($(git diff --cached --name-only HEAD))

for i in "${filenames[@]}"
do
    if [[ $i =~ \.js$ ]] || [[ $i =~ \.jsx$ ]] ;
    then
        echo node_modules/eslint/bin/eslint.js -c .eslintrc $i
        node_modules/eslint/bin/eslint.js -c .eslintrc $i
        if [ $? -ne 0 ];
        then
            exit 1
        fi
    fi
done
```

### CODE REVIEW

**Comment by bnaul** [comment]
We're using `sklearn.externals.joblib` elsewhere, I think we should stick to that for consistency unless there's a reason to change. In which case we should change it everywhere.

**Comment by acrellin** [comment]
:tada: :green_apple:

**Comment by acrellin** [comment]
Looks like we actually do need `joblib` even if we're not directly importing it.

**Comment by bnaul** [comment]
How so?

**Comment by acrellin** [comment]
```
Traceback (most recent call last):
  File "services/task_server.py", line 95, in report_result
    result = yield future._result()
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/distributed/client.py", line 129, in _result
    six.reraise(*clean_exception(**d))
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 459, in load
    obj = unpickler.load()
  File "/opt/python/3.5.0/lib/python3.5/pickle.py", line 1039, in load
    dispatch[key[0]](self)
  File "/opt/python/3.5.0/lib/python3.5/pickle.py", line 1326, in load_global
    klass = self.find_class(module, name)
  File "/opt/python/3.5.0/lib/python3.5/pickle.py", line 1376, in find_class
    __import__(module, level=0)
ImportError: No module named 'joblib'
```

**Comment by acrellin** [comment]
https://travis-ci.org/cesium-ml/cesium_web/builds/159734067#L1544

**Comment by acrellin** [comment]
Which makes sense - `sklearn` is essentially just wrapping it, so it needs to be imported still

**Comment by bnaul** [comment]
No, that doesn't make sense...the whole point of `sklearn.externals` is that it contains those libraries so separate dependencies aren't required: https://github.com/scikit-learn/scikit-learn/tree/master/sklearn/externals/joblib

**Comment by acrellin** [comment]
Do you have any idea why we'd be seeing the above error?

**Comment by bnaul** [comment]
Maybe `distributed` or something secretly depends on `joblib`...?

**Comment by acrellin** [comment]
In any case, I'm adding it back to requirements.txt for now so the tests will pass. I can open an issue to look into it if you want.

**Comment by bnaul** [comment]
Oh, the problem is that the test data was made with a different version of `joblib`. This is why having static test data stored in version control is bad...I fixed it in my PR to @stefanv's branch, so for now leave it like this and I'll remove it later.

Otherwise this is 👍  for me but I don't know enough to really judge; will leave it to @stefanv to merge.

**Comment by acrellin** [comment]
:green_apple: :green_heart: :dollar: 
Ok @stefanv, this is ready for your review.

**Comment by stefanv** [comment]
Thanks, Ari, this looks great.  Can you make another PR with the commit hook + instructions in the README, so that we have that on record?

**Pull request merged**
