### PR TITLE
Allow for prediction of subset of a dataset by specifying TS names

### PR DESCRIPTION
**Pull request by acrellin**

### CODE REVIEW

**Comment by bnaul** [comment]
Seems reasonable to me :+1:

**Comment by acrellin** [comment]
@stefanv any comments, or good to go?

**Comment by stefanv** [comment]
This looks fine; but where is this used from?

**Comment by acrellin** [comment]
@stefanv, the survey classifier app uses this.

**Comment by stefanv** [comment]
Can we document this somewhere, perhaps?  I don't think we have any endpoint docs currently, but perhaps that'd be a good idea.

**Comment by stefanv** [comment]
Or, at least test it, so we do not break it?

**Comment by stefanv** [comment]
Rebasing on master should make pep8 quieter.

**Pull request merged**
