### PR TITLE
Add test for sequential execution of whole pipeline

### PR DESCRIPTION
**Pull request by acrellin**

### CODE REVIEW

**Comment by bnaul** [comment]
Gonna go ahead and merge this so that we can have it for the other outstanding PRs.

**Comment by bnaul** [comment]
@acrellin only question, are the sleeps in this reliably going to pass? We had some issues with that before.

**Comment by acrellin** [comment]
@bnaul there's only one `time.sleep` call, which I just copied over from an existing test. We probably don't even need that part, actually. Or do you mean the `implicitly_wait`s?

**Comment by bnaul** [comment]
Yeah either one. I assume it's all the same as other tests, right?

**Comment by acrellin** [comment]
Yeah, except that I dropped the `implicitly_wait` for the prediction to finish from 30 to 10 seconds.

**Comment by acrellin** [comment]
:sparkles:

**Pull request merged**
