### PR TITLE
Use imp for faster import checking

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by bnaul** [comment]
@stefanv are you happy with this? Shall I merge?

**Comment by stefanv** [comment]
Shall I update to check version with pip instead?

**Comment by bnaul** [comment]
What would the difference be between that and just running `pip install -r requirements.txt`? Can't remember now we why we don't just do that...

**Comment by stefanv** [comment]
It takes long, and when you're debugging the web server, that 1.5 second
delay is quite annoying.  It also requires an internet connection, so
not good for on a plane.

**Comment by bnaul** [comment]
```
$ time pip install -r requirements.txt
pip install -r requirements.txt  0.59s user 0.09s system 87% cpu 0.777 total
```

It only requires internet if you don't have the necessary dependencies, in which case anything is going to fail. Definitely think we should do that instead of rolling our own failure-prone script to shave off 1/2 a second...

**Comment by stefanv** [comment]
You're right; this is faster than I thought it would be.  OK, let's go with that.

**Pull request closed without merging**
