### PR TITLE
Update Docker config for new architecture

### LINKED ISSUE #149: Create Docker image with latest Cesium
And verify that everything works as intended.

### PR DESCRIPTION
**Pull request by bnaul**
Still need to automate the testing+push process on Travis, but that can come later.

Fixes #149.

### CODE REVIEW

**Comment by bnaul** [comment]
This should be good to go.

Also, regarding testing: just running `cesium_app/tests/frontend/test_pipeline_sequentially.py` against Docker would be a good option for our automatic build, it does a single click-through of everything using data on disk (not fixture data injected into the DB, which is tricker to do from outside the Docker container)

**Comment by bnaul** [comment]
Let's go with @hatsy's db setup unless you strongly prefer the old way @stefanv

**Comment by bnaul** [comment]
@stefanv one other question: is the Docker 5000 redirected to 9000 because you wanted to keep them separate, or is that because you use 9000 instead of 5000?

**Comment by stefanv** [comment]
5000 turns out to be a fairly commonly used port for multiple projects, including Pelican, which we use for the blog :)  Although, they seem to have shifted to 8000.

**Comment by stefanv** [comment]
:+1:

**Pull request merged**
